### PR TITLE
Added zsh completion file

### PR DESCRIPTION
**Pull request by Foxboron**
Started working on a better zsh completion file. It's not perfect as it's not able to complete all flags for the second subcommand like `gopass audit hibp`. But it's a lot better then the current state of things.

Please review and check for spelling mistakes or errors :)

Refference: #557

Signed-off-by: Morten Linderud <morten@linderud.pw>

### CODE REVIEW

**Comment by Foxboron** [comment]
I forgot to fix the makefile. I'll get on it when i have time :)

**Comment by dominikschulz** [comment]
This looks ok by itself, but we'd have to maintain it Everytime we change the commands.
Could we maybe just generate this (and the fish completion) somehow?

**Comment by Foxboron** [comment]
I have no idea how that would work sadly.

**Comment by dominikschulz** [comment]
Please see #565 for my current approach to generating zsh (and possily fish) completion scripts.
This needs some more work (wrt. flags), but once completed this should enable us to generate shell completion scripts that neither rely on bash nor have to be kept manually in sync.

**Comment by Foxboron** [comment]
@dominikschulz woah, super neat! I'll take a look later this evening and test the generated zsh completion.

**Comment by Foxboron** [comment]
This is superseded by #565

**Pull request closed without merging**
