### PR TITLE
fix clone section

### PR DESCRIPTION
**Pull request by netmonk**
gopass clone doesn't work to import existing pass repo. fixed by add git between gopass and clone.

### CODE REVIEW

**Comment by dominikschulz** [comment]
`gopass clone` does a lot more that a `gopass git clone`.
Will need to carefully check this first.

**Comment by netmonk** [comment]
well from my experience gopass clone does nothing. 
`toto@archiplonk:~$ gopass init
[init] Initializing a new password store ...
Please select a private key for encrypting secrets:
[0] 0xC5BEE00F9BA7C3A8 - toto@toto.com
[1] 0x06B5AF0D6EE6F5EC - titi@toto.com
Please enter the number of a key (0-1) [0]: 0
[init] Initializing git repository ...
Use toto@toto.com for password store git config? [Y/n]: 
[init] Git initialized
[init] Password store /home/toto/.password-store initialized for:
[init]   0xC5BEE00F9BA7C3A8 - toto@toto.com
toto@archiplonk:~$ 
toto@archiplonk:~$ 
toto@archiplonk:~$ 
toto@archiplonk:~$ 
toto@archiplonk:~$ 
toto@archiplonk:~$ 
toto@archiplonk:~$ gopass clone ssh://git@xxxx:2222/bigdata/passwords.git

Error: Can not clone ssh://git@xxxx:2222/bigdata/passwords.git to the root store, as this store is already initialized. Please try cloning to a submount: `gopass clone ssh://git@xxxx:2222/bigdata/passwords.git sub`
toto@archiplonk:~$ gopass git clone ssh://git@xxxx:2222/bigdata/passwords.git
[root]Running git clone ssh://git@xxxx:2222/bigdata/passwords.git
`

**Comment by netmonk** [comment]
what i want is to import an existing password store, from a git repo to be my root repo. 
when i ` gopass clone` directly it failed because the root store is not initialised. 
Once i initialised using simply `gopass init` the root store, im unable to correctly import the remote password store as local root one. 
This become even more complicated as i need to clone a second one.

**Comment by dominikschulz** [comment]
`gopass clone` should be fine.

Starting without any root store (i.e. `rm -rf ~/.password-store`)
```
# initialize root store
gopass clone git@github.com:some/store.git
# clone and add mount "other"
gopass clone git@github.com:some/other-store.git other
```

Running `gopass git clone` is possible but not recommended as it it's missing some features.

If you need further help feel free to open an issue.

**Comment by netmonk** [comment]
well, if gopass clone were working, i wouldn't mind to dig further. 
what happens then, is that gopass complain that i cannot clone a store which is not initialised first. 
So simply using `gopass clone` alone isn't working.

**Comment by dominikschulz** [comment]
In my tests `gopass clone` did not complain about an unintialized store. Quite the contrary it will complain if the store is already initialized.

I'd like to ask you to try with the latest release (1.5.1) or a build from master and raise an issue if you still observe this problem because I wasn't able to reproduce it.

**Comment by netmonk** [comment]
toto@archiplonk:~/work$ gopass --version 
gopass 1.5.1 (10c2866255a2bfd40cc9f328ed1101d934e11b77) go1.9 linux amd64

**Comment by netmonk** [comment]
Well, i dont know what happened, but, it worked just few minutes ago. although im looking very seriously to my shell history, i dont see any difference between today and yesterday. 

Thank you for your support anyway ! :)

**Pull request closed without merging**
