### PR TITLE
Drop unnecessary type conversions

### PR DESCRIPTION
**Pull request by ferhatelmas**
Reported by unconvert linter.

### CODE REVIEW

**Comment by ferhatelmas** [comment]
If you want to integrate it, I can add it in a separate PR.

**Comment by dominikschulz** [comment]
Yes, that would be nice.

**Comment by ferhatelmas** [comment]
I just came to add unconvert but it's already done by you :+1: 

How about using gometalinter to run all these linters so as to have smaller make file.

**Comment by dominikschulz** [comment]
Hey, I'm sorry if you were about to open a PR. I was trying to fix a bug in the Makefile and just added this at the same time.

Gometalinter is interesting, but we had some trouble with that at work and I'd prefer to stick to the explicit approach we use right now.

**Comment by ferhatelmas** [comment]
No worries, I will try to make myself useful in other parts.

**Pull request merged**
