### PR TITLE
Ksh completion

### PR DESCRIPTION
**Pull request by qbit**
This adds support for outputting completion for OpenBSD's ksh. I am a bit hesitant to keep the current name.. as other ksh implementations don't have completion.. so it might be better to make it "openbsdksh" or "oksh".. Wanted to get everyone's opinion on that one..

### CODE REVIEW

**Comment by dominikschulz** [comment]
I'd go for `openbsdksh`. `oksh` sounds vague to me.

**Comment by qbit** [comment]
OK, renamed it to `openbsdksh`.

**Comment by dominikschulz** [comment]
The build seems to be failing due to an outdated reference in the command struct. Could you please check and rebase? Thanks!

**Comment by qbit** [comment]
Should be good now.

**Comment by qbit** [comment]
Crap - looks like the `test` target is busted on OpenBSD - my tests were not hitting the actions stuff.

**Comment by qbit** [comment]
OK to include something like this? :

``` diff
diff --git a/Makefile b/Makefile
index 5d641f5..6ce6e57 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,7 @@
 FIRST_GOPATH              := $(firstword $(subst :, ,$(GOPATH)))
 PKGS                      := $(shell go list ./... | grep -v /tests)
-GOFILES_NOVENDOR          := $(shell find . -type f -name '*.go' -not -path "./vendor/*")
-GOFILES_NOTEST            := $(shell find . -type f -name '*.go' -not -path "./vendor/*" -not -name "*_test.go")
+GOFILES_NOVENDOR          := $(shell find . -type f -name '*.go' | grep -v "./vendor/")
+GOFILES_NOTEST            := $(shell find . -type f -name '*.go' | grep -v "./vendor/" | grep -v "_test.go")
 GOPASS_VERSION            ?= $(shell cat VERSION)
 GOPASS_OUTPUT             ?= gopass
 GOPASS_REVISION           := $(shell cat COMMIT 2>/dev/null || git rev-parse --short=8 HEAD)
@@ -117,7 +117,7 @@ $(FISH_COMPLETION_OUTPUT): build
 	@echo -n ">> FISH COMPLETION, output = $(FISH_COMPLETION_OUTPUT)"
 	@./gopass completion fish > $(FISH_COMPLETION_OUTPUT)
 	@$(call ok)
-	
+
 $(ZSH_COMPLETION_OUTPUT): build
 	@echo -n ">> ZSH COMPLETION, output = $(ZSH_COMPLETION_OUTPUT)"
 	@./gopass completion zsh > $(ZSH_COMPLETION_OUTPUT)
```

**Pull request merged**
