### PR TITLE
adding rofi completion

### PR DESCRIPTION
**Pull request by deadc0de6**
This is a simple copy of the dmenu block for rofi.

It will call ```rofi --dmenu``` to choose which entry to display

### CODE REVIEW

**Comment by deadc0de6** [comment]
First time in go. Hope it helps

**Comment by metalmatze** [comment]
Yes. I saw the duplication too. I will merge this and then try to work on making it DRY. Ok?

**Comment by deadc0de6** [comment]
ok, thanks for your help !

**Comment by metalmatze** [comment]
I'm not going to merge this as it it. We're currently thinking about making the approach more general, so it really doesn't matter if one uses dmenu or rofi, or whatever.

**Pull request closed without merging**
