### PR TITLE
Add support for YAML metadata parsing

### PR DESCRIPTION
**Pull request by bumi**
This allows loading a specified key from a as yaml formatted metadata part of a secret. (related issue: #112 )

## Usage: 

assuming the following secret:

```
password

yaml: mammal
name: Johne Doe
```

### Display the value of a specified key:
```bash
gopass show yaml-example --key [yaml key]
```
### Copy the value of a specified key:
```bash
gopass show yaml-example -k [yaml key] -c 
```

When the `-k/--key` option is given the first line (the password) of a secret will be ignored and the rest will be loaded using [simpleyaml](https://github.com/smallfish/simpleyaml/). The `--clip` and `--qr` flags are still supported and the value the `--key` will be used. 

Editing the metadata part is currently not supported. In my usecase editing would mostly be manual and yaml is easy enough to write. So I don't think that this is super important. 

I am opening this PR for discussion on how this feature should be implemented. 
This is my first piece of go code that I am writing... so I don't really know what I am doing yet :) 

## ToDo:

- [ ] support any type of value in the YAML (currently strings are assumed)

### CODE REVIEW

**Comment by dominikschulz** [comment]
Thanks a lot for the PR.

At first sight this looks like going into the right direction, but still lacking a lot in terms of UX. Will give this some more thought / comments soon.

**Comment by bumi** [comment]
thanks, looking forward to your thoughts.

**Comment by dominikschulz** [comment]
Closing in favour of #125 

Thank you very much for this PR. If this was your first attempt in Go it's definitely very good. We wanted to some things a little different and also include write support so I thought it would be easier if we just pick your approach and implement it directly.

**Comment by bumi** [comment]
whooot! awesome! will check it out. thanks!

**Pull request closed without merging**
